runtime: custom
env: flex

includes:
- env_variables.yaml

health_check:
  enable_health_check: False
  check_interval_sec: 60
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

beta_settings:
  cloud_sql_instances: leeg-240122:us-central1:matches-na

manual_scaling:
  instances: 1

network:
  name: default