package org.dmcfalls.leeg.domain.uri;

public enum PickBanUriEnum {
    SESSION,
    PICKABLE_CHAMPIONS,
    BANNABLE_CHAMPIONS,
    DISABLED_CHAMPIONS,
    TEAM_BUILDER_LOBBY_SESSION,
    TEAM_BUILDER_LOBBY_PICKABLE_CHAMPIONS,
    TEAM_BUILDER_LOBBY_BANNABLE_CHAMPIONS,
    TEAM_BUILDER_LOBBY_DISABLED_CHAMPIONS,
    UNKNOWN
}
