[package]
name = "reqs"
version = "0.1.0"
authors = ["dmcfalls <dan.mcfalls4@gmail.com>"]

[lib]
name = "reqs"
path = "src/lib.rs"

[[bin]]
name = "reqsbin"
path = "src/main.rs"

[dependencies]
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.39"
csv = "1.0.7"
