[package]
name = "banana"
version = "0.1.0"
authors = ["Alex Sherman <me.alexsherman@gmail.com>"]
edition = "2018"

[dependencies]
reqs = { path = "../reqs"}
rocket = "0.4.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "postgres_pool"]

